<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'seller_id',
        'name',
        'price',
        'description'
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('seller', function ($query) {
            if (auth()->user()) {
                if (\Illuminate\Support\Facades\Auth::user()->hasRole(User::$ROLE_SELLER_ID)) {
                    $query->where('seller_id', auth()->user()->id);
                }
            }
        });
    }

}
